### ISSUE TITLE
The namespace and the static class have the same name

### ISSUE THREAD

**Issue by Thf772** [ygorhenrique/Asynq#1]
The namespace `Asynq` has the same name as the static class `Asynq` causing a compiler error: `error CS0234: The type or namespace name 'WhenAll' does not exist in the namespace 'Asynq' (are you missing an assembly reference?)`

This happens when attempting to use the following code:
```csharp
using Asynq;

// class & method definition
        await Asynq.WhenAll(arrayOfValueTasks);
```

The compiler assumes `Asynq` in the await expression to refer to the namespace insted of the class.

I would suggest renaming the namespace and not the class, since the class will be used much more than the namespace.

**Comment by ygorhenrique** [comment]
hey @Thf772 thanks for the heads up, I've adjusted the library.
We've opted for keeping the namespace & changing only the class name since it was not really in usage yet by any clients due to the error mentioned above. That also helps us with some consistency in-between classes.

Cheers

**Comment by ygorhenrique** [comment]
hey @Thf772 thanks for the heads up, I've adjusted the library.
We've opted for keeping the namespace & changing only the class name since it was not really in usage yet by any clients due to the error mentioned above. That also helps us with some consistency in-between classes.

Cheers
